### ISSUE TITLE
Response to Soren's Comments in the Push 

### ISSUE THREAD

**Issue by wflewis12** [wflewis12/Causal_ML_Project#1]
I wasn't sure how to respond to Soren's comments on his push, so I thought I would respond here so that everyone can communicate in one place. Let me know if this doesn't work for people, I'm happy to send emails instead. 

I think that option one as written on the push won't work well, as it ends up being (essentially) just propensity score matching -- which we were advised against in class. 

I agree that 2 & 3 are likely going to be roughly equivalent. I have been having some success training a single model across 1996-1997, then estimating all expected values from that single model. I think that this may be better than computing 2 & 3 separately because it extends more naturally to the case where we want to compute our ATT for every year in our sample. Furthermore, if there are some interaction effects between year, under19 and insurance rates which change over time, it seems that a single model would be able to pick up on that effect better than a number of smaller models (which cannot share info). 

For the issue with covariates (i.e. irish men in 1996 vs. 1997) I think that that comes down to an issue of overlap. If one demographic (i.e. combination of covariates) only appears in the treated/untreated group, then we'll never have identification in a DiD setup. Also, it's definitely something which we can check empirically (just look to see if a fitted propensity score estimate ever equals 0 or 1). 

In terms of the # of 14 y/o's vs. # of 20 y/o's, I think that that comes down to our assumptions about how the people were sampled. I'm pretty sure that the CPS data is drawn from a random sample of people, so if we look at # of 19y/o's in the data for 2000 -- the proportion should roughly match the proportion of 19 y/o's in 2000 in the population. If you mean that we might be concerned that the population distribution changes over time, I don't have a great answer to that. I think to get identification, we'll probably need to assume no serious changes in distribution over time. That said, I'm not sure about that yet -- and that's all conjecture. 

Let me know what you all think!

**Comment by sorendunn** [comment]
Sorry on reflection that was probably not the best place to put it - I'm still getting used to GitHub. You're right that I was thinking too much in the frame of the regular differences in differences set-up compared to our case when different people are sampled in each year. I am still not sure about how that conversion works, but I'll just press on for now. I'm pretty sure I have the k-fold working so I'll try to integrate that into your code when you get a chance to push it.

Cheers!
